# Generated by Django 4.0.8 on 2022-12-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhome', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client1_registration',
        ),
    ]
