# Generated by Django 4.0.8 on 2022-12-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client1_registration',
            name='report',
            field=models.BooleanField(default=False),
        ),
    ]
