# Generated by Django 4.0.8 on 2023-01-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitering', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='client1_registration',
            new_name='moniter1_registration',
        ),
    ]
