# Generated by Django 4.0.8 on 2023-01-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitering', '0002_rename_client1_registration_moniter1_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moniter1_registration',
            name='report',
        ),
    ]
